before_script:
# copy config
- cp my_php.ini /usr/local/etc/php/conf.d/test.ini
# Install dependencies
- bash ci/docker_install.sh > /dev/null

# We test PHP5.6
test:5.6:
  image: php:5.6
  script:
  - phpunit --configuration phpunit_myapp.xml

# We test PHP7.2.13 (good luck with that)
test:7.2.13:
  image: php:7.2.13
  script:
  - phpunit --configuration phpunit_myapp.xml
